### ISSUE TITLE
Module stopped working...yahoo error 

### ISSUE THREAD

**Issue by mariuszkobak** [Santanachia/MMM-SmokedMirror#2]
This module was working great 3 weeks ago.
Right now data is not loading. 
When I start mm by 'npm start dev' I can see in logs that there is an error related to yahoo api.

@Santanachia can you please verify that?

**Comment by Santanachia** [comment]
Yahoo turned off YQL functionality that i use :/
i'll try to fix it

**Comment by mariuszkobak** [comment]
Hey @Santanachia any progress on this issue? :)

**Comment by Santanachia** [comment]
Hi,
it's repaired. Let me know if it works fine.
prepare the masks, WINTER is coming ;)

**Comment by Santanachia** [comment]
p.s. @mariuszkobak, could you take a look at new brunch - [noYQL](https://github.com/Santanachia/MMM-SmokedMirror/tree/noYQL)? I've just change a way of gathering data.

**Comment by mariuszkobak** [comment]
Works really well now. Thanks for this update :)
