### ISSUE TITLE
Stacje GIOŚ

### ISSUE THREAD

**Issue by badgerman11** [Santanachia/MMM-SmokedMirror#6]
Cześć,
Czy próbowałeś już pobierać dane ze stacji GIOŚ?

**Comment by Santanachia** [comment]
tak było do [98298722] ale zrezygnowałem z GIOŚ, bo dane są zbyt rzadko aktualizowane, przy większych stężeniach przestają w ogóle pokazywać no i czujników tyle co kot napłakał

**Comment by badgerman11** [comment]
DziękI! Pewnie wszystko zależy od lokalizacji, w większych miastach sporo mają stacji. Niestety ich pomiary są jedynymi miarodajnymi, gdyż nie są zależne od wilgotności i temperatury (tak jak np Airly), a teraz aktualizacja jest co godzinę.

**Comment by Santanachia** [comment]
Warszawa: 5 stacji GIOŚ w tym jedna nieczynna; kilkaset czujników Airly
do tego stacje GIOŚ są ustawione przy samej drodze gdzie większość pyłu jest uniesiona z drogi, co nie daje poprawnych wyników już 2 bloki dalej

**Comment by badgerman11** [comment]
Czujniki Airly z tego co wiem oparte są na w większości na chińskich PMSx003 (przynajmniej tak było na początku, może coś się zmieniło). Czujnik bada przezierność powietrza i na tej podstawie określa stężenia pyłów. Dodatkowo pomiar jest przekłamywany w przypadku wilgotności powyżej 80% i przy ujemnej temperaturze (czyli np w większość dni w zimie). GIOŚ ma teraz 8 stacji w w-wie, lokalizacja przy ulicach moim zdaniem lepsza, niż gdyby były umieszczone w przewiewnych miejscach, bo przynajmniej wynik zawyżony, a nie zaniżony. Dodatkowo pomiar następuje poprzez podgrzanie próbki powietrza do (chyba) 20 stopni i odciągnięciu z niej pary wodnej, co daje dużo większa dokładność pomiaru i jego powtarzalność. Oczywiście nie piszę, że jedne są lepsze od drugich, bo obie stacje są pomocne. Jednych jest więcej i mniej dokładnych, drugich jest bardzo mało ale są dokładne. Dlatego też fajnie je mieć razem, szczególnie jak poziom smogu sprawdzasz, żeby twoje dziecko nie wciągało tego syfu i nie wychodziło na dwór jak jest za wysokie ;) Spróbuje podziałać na tej wcześniejszej wersji ale jakbyś jednak pomyślał nad zrobieniem modułu ze stężeniem ze stacji GIOŚ (np podającą procent normy stężania), to będę Ci bardzo kibicował! Dopiero się uczę tego języka, więc nieprędko uda mi się coś takiego napisać ;)

**Comment by Santanachia** [comment]
z jednej strony racja, ale z drugiej, co mi po pomiarze na Niepodległości (najbliższa mi stacja przed ostatnią zimą), gdy dom i żłobek mam na Bemowie? Co mi po pomiarze przy samej drodze, gdy dziecko przeprowadzam z jednej strony parku na drugą?

postaram się w wolnej chwili dać możliwość wyboru GIOŚ/Airy, ale póki co, stara wersja powinna działać i też ma wartości oraz % normy.

**Comment by badgerman11** [comment]
Można sobie średnią wyciągać ;)

Dzięki, wypróbuje to dzisiaj!
